plugins {
	id 'org.springframework.boot' version '4.0.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.jetbrains.kotlin.jvm' version '2.3.0'
	id 'org.jetbrains.kotlin.plugin.spring' version '2.3.0'
}

version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

kotlin {
	jvmToolchain(25)
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'com.fasterxml.jackson.module:jackson-module-kotlin'
	implementation 'org.jetbrains.kotlin:kotlin-reflect'
	implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
	implementation 'io.projectreactor.kotlin:reactor-kotlin-extensions'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'

	// Infrastructure
	implementation 'io.searchbox:jest:6.3.1'

	// Arrow
	implementation 'io.arrow-kt:arrow-core:2.1.2'

	// Assertj.
	testImplementation 'org.assertj:assertj-core:3.27.6'

	// JSONAssert.
	testImplementation 'org.skyscreamer:jsonassert:1.5.3'

	// Kluent: fluent interface for tests.
	testImplementation('org.amshove.kluent:kluent:1.73')

	// Kotlin test
	testImplementation("org.jetbrains.kotlin:kotlin-test")
	testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
}

compileKotlin {
	kotlinOptions {
		freeCompilerArgs = ['-Xjsr305=strict']
		jvmTarget = '25'
	}
}

compileTestKotlin {
	kotlinOptions {
		freeCompilerArgs = ['-Xjsr305=strict']
		jvmTarget = '25'
	}
}

tasks.withType(Test).configureEach {
	useJUnitPlatform()
}
