
server:
  port: 8000

spring:
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false
  main:
    allow-bean-definition-overriding: true